# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "github-actions"  # For GitHub Actions
    directory: "/"  # Location of package manifests
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"  # For Node.js dependencies
    directory: "/"  # Location of package manifests
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"  # For Docker images
    directory: "/"  # Location of Docker manifests
    schedule:
      interval: "daily"
